#!/bin/sh
# Copyright (c) 2012-2013 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Written by Mikolaj Izdebski <mizdebsk@redhat.com>

set -e

name=xmvn
ver=$(git tag | tail -1)

if [ -z "${ver}" ];then
    echo "No git tags found" >&2
    exit 1
fi

tarball=${name}-${ver}.tar.xz
git archive -v --prefix=${name}-${ver}/ ${ver} | xz >${tarball}

read -e -p "Upload ${tarball} to fedorahosted.org? (y/N): "
if [ "$REPLY" = y ]; then
    git push --tags
    scp ${tarball} fedorahosted.org:${name}
fi
