#!/bin/sh
# Copyright (c) 2013-2023 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Written by Mikolaj Izdebski <mizdebsk@redhat.com>

# Upload site to stagging area
set -e

if [ ! -d target/site ]; then
    echo "$0: Site wasn't built." >&2
    echo "$0: You may want to run 'mvn clean verify site' first." >&2
    exit 1
fi

tar cC target site | gzip -9 | ssh fedorapeople.org "cd public_html/xmvn/stage && rm -rf site && tar xzv"
