#!/bin/sh
# Copyright (c) 2014-2019 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Written by Mikolaj Izdebski <mizdebsk@redhat.com>

set -e

export XDG_CONFIG_DIRS=$PWD/target/root/etc/xdg
export XDG_DATA_DIRS=:
export XDG_CONFIG_HOME=:
export XDG_DATA_HOME=:

mvn clean verify

cat target/apache-maven-3.1.0/build.log
